#!/usr/bin/env bun
/**
 * Exa AI search CLI - Generated from MCP tools
 *
 * Auto-generated by @bunli/plugin-mcp
 * Do not edit manually - regenerate with: bun test test/e2e/exa-mcp.test.ts --update
 */

import { createCLI, defineCommand, option } from '@bunli/core'
import { Client } from '@modelcontextprotocol/sdk/client/index.js'
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js'
import { z } from 'zod'

// Check for required environment variable
const EXA_API_KEY = process.env.EXA_API_KEY
if (!EXA_API_KEY) {
  console.error('Error: EXA_API_KEY environment variable is required')
  process.exit(1)
}

// MCP client helper
async function callTool(toolName: string, args: Record<string, unknown>) {
  const transport = new StdioClientTransport({
    command: 'npx',
    args: ["-y","exa-mcp-server"],
    env: { ...process.env, EXA_API_KEY: EXA_API_KEY! }
  })

  const client = new Client(
    { name: 'exa-cli', version: '1.0.0' },
    { capabilities: {} }
  )

  await client.connect(transport)

  try {
    const result = await client.callTool({ name: toolName, arguments: args })
    return result
  } finally {
    await client.close()
  }
}

// Commands
const CompanyResearchExaCommand = defineCommand({
  name: 'exa:company-research-exa',
  description: 'Research companies using Exa AI - finds comprehensive information about businesses, organizations, and corporations. Provides insights into company operations, news, financial information, and industry analysis.',
  options: {
    'company-name': option(z.string(), {
      description: 'Name of the company to research'
    }),
    'num-results': option(z.coerce.number().optional(), {
      description: 'Number of search results to return (default: 5)'
    }),
  },
  async handler({ flags }) {
    const result = await callTool('company_research_exa', flags as Record<string, unknown>)
    console.log(JSON.stringify(result, null, 2))
  }
})

const GetCodeContextExaCommand = defineCommand({
  name: 'exa:get-code-context-exa',
  description: 'Search and get relevant context for any programming task. Exa-code has the highest quality and freshest context for libraries, SDKs, and APIs. Use this tool for ANY question or task for related to programming. RULE: when the user\'s query contains exa-code or anything related to code, you MUST use this tool.',
  options: {
    'query': option(z.string(), {
      description: 'Search query to find relevant context for APIs, Libraries, and SDKs. For example, \'React useState hook examples\', \'Python pandas dataframe filtering\', \'Express.js middleware\', \'Next js partial prerendering configuration\''
    }),
    'tokens-num': option(z.coerce.number().min(1000).max(50000).default(5000), {
      description: 'Number of tokens to return (1000-50000). Default is 5000 tokens. Adjust this value based on how much context you need - use lower values for focused queries and higher values for comprehensive documentation.'
    }),
  },
  async handler({ flags }) {
    const result = await callTool('get_code_context_exa', flags as Record<string, unknown>)
    console.log(JSON.stringify(result, null, 2))
  }
})

const WebSearchExaCommand = defineCommand({
  name: 'exa:web-search-exa',
  description: 'Search the web using Exa AI - performs real-time web searches and can scrape content from specific URLs. Supports configurable result counts and returns the content from the most relevant websites.',
  options: {
    'context-max-characters': option(z.coerce.number().optional(), {
      description: 'Maximum characters for context string optimized for LLMs (default: 10000)'
    }),
    'livecrawl': option(z.enum(['fallback', 'preferred']).optional(), {
      description: 'Live crawl mode - \'fallback\': use live crawling as backup if cached content unavailable, \'preferred\': prioritize live crawling (default: \'fallback\')'
    }),
    'num-results': option(z.coerce.number().optional(), {
      description: 'Number of search results to return (default: 8)'
    }),
    'query': option(z.string(), {
      description: 'Websearch query'
    }),
    'type': option(z.enum(['auto', 'fast', 'deep']).optional(), {
      description: 'Search type - \'auto\': balanced search (default), \'fast\': quick results, \'deep\': comprehensive search'
    }),
  },
  async handler({ flags }) {
    const result = await callTool('web_search_exa', flags as Record<string, unknown>)
    console.log(JSON.stringify(result, null, 2))
  }
})

// CLI setup
const cli = await createCLI({
  name: 'exa-cli',
  version: '0.0.0',
  description: 'Exa AI search CLI - Generated from MCP tools'
})

cli.command(CompanyResearchExaCommand)
cli.command(GetCodeContextExaCommand)
cli.command(WebSearchExaCommand)

// Run the CLI
await cli.run()